## 2nd july (import math module)

In [3]:
x=sqrt(25)        #sqrt is imbuild function

NameError: name 'sqrt' is not defined

In [4]:
import math    #math is module

In [5]:
x=math.sqrt(25)
x

5.0

In [6]:
x1=math.sqrt(15)
x1

3.872983346207417

In [8]:
print(math.floor(2.9))   ## floor -min or least value

2


In [9]:
print(math.ceil(2.9))   #ceil-max or hughest value

3


In [10]:
print(math.pow(3,2))

9.0


In [11]:
print(math.pi)   #these are constant

3.141592653589793


In [12]:
print(math.e)   #these are constant

2.718281828459045


In [13]:
import math as m
m.sqrt(10)

3.1622776601683795

In [15]:
from math import sqrt,pow   #math has many function if you want to call specific function then you use from
pow(2,3)

8.0

In [16]:
round(pow(2,3))

8

In [17]:
#help(math)

In [ ]:
#pycharm run debug
# how to install python idle
#how to install pycharm & starts working on pycharm

In [19]:
x=input()
y=input()
z=x+y
print(z)

 2
 3


23


In [20]:
x1=input('Enter the 1st number')
y1=input('Enter the 2nd number')
z1=x1+y1
print(z1)

Enter the 1st number 5
Enter the 2nd number 6


56


In [21]:
type(x1)
type(y1)

str

In [22]:
x1=input('Enter the 1st number')
a1=int(x1)
y1=input('Enter the 2nd number')
b1=int(y1)
z1=a1+b1
print(z1)

Enter the 1st number 4
Enter the 2nd number 5


9


In [23]:
x2=int(input('Enter the 1st number'))
y2=int(input('Enter the 2nd number'))    #by using less memory than compared to the previous code
z2=x2+y2
z2

Enter the 1st number 4
Enter the 2nd number 5


9

In [24]:
ch=input('enter a char')
print(ch)

enter a char a


a


In [29]:
ch=input('enter a char')
print(ch)

enter a char shabbi


shabbi


In [30]:
print(ch[0])

s


In [31]:
print(ch[1])

h


In [32]:
print(ch[-1])

i


In [33]:
ch=input('enter a char')[0]
print(ch)

enter a char Shabi


S


In [34]:
ch=input('enter a char')[1:3]
print(ch)

enter a char Shabi


ha


In [35]:
ch=input('enter a char')
print(ch)

enter a char Shabi


Shabi


In [36]:
ch=input('enter a char')
print(ch)

enter a char 2+6-1


2+6-1


In [37]:
result=eval(input('enter an expr'))
print(result)

enter an expr 5*2


10


## 3rd july(class)

In [39]:
import numpy as np

In [40]:
np.__version__

'1.26.4'

In [41]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [42]:
type(my_list)

list

In [43]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [44]:
type(arr)

numpy.ndarray

In [45]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [48]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [49]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [50]:
np.arange(10,30,30,3)

TypeError: Cannot interpret '3' as a data type

In [51]:
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [52]:
np.arange(20,8)

array([], dtype=int32)

In [53]:
np.arange(-20,8)   #1st arg < 2nd arg

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [54]:
n=np.arange(-20,8)
n

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [29]:
np.zeros(3)

array([0., 0., 0.])

In [30]:
np.zeros(3,dtype=int)    

array([0, 0, 0])

In [32]:
z=np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [33]:
z=np.zeros(5,dtype=int)
z

array([0, 0, 0, 0, 0])

In [36]:
z=np.zeros((2,2))    ##2d array
z

array([[0., 0.],
       [0., 0.]])

In [38]:
z=np.zeros((3,3),dtype=int) 
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
z=np.zeros((5,9),dtype=int)
z

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [40]:
z=np.ones((5,9),dtype=int)
z

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [41]:
z=np.ones(3)
z

array([1., 1., 1.])

In [42]:
z=np.ones((3,3),dtype=int)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [49]:
nd1=np.ones((10,10),dtype=int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [48]:
arr

array([0, 1, 2, 3, 4, 5])

## 3rd task  